### ISSUE TITLE
Implement Main Dashboard UI Components

### ISSUE THREAD

**Issue by jreyes-beyond** [jreyes-beyond/lexarb#6]
### Features to Implement:
1. Statistics Cards
   - Active Cases Counter
   - Pending Documents
   - Upcoming Deadlines
   
2. Recent Cases List
   - Case ID
   - Status
   - Last Updated
   - Quick Actions

3. Quick Actions Panel
   - New Case
   - Upload Documents
   - Schedule Meeting

### Technical Requirements:
- Use shadcn/ui components
- Implement with React + TypeScript
- Style with Tailwind CSS using our custom colors:
  ```js
  colors: {
    primary: {
      DEFAULT: "#0047AB",
      dark: "#00308F",
    },
    secondary: {
      DEFAULT: "#FFB347",
      light: "#FFA07A",
    },
  }
  ```

### Tasks:
- [ ] Create base layout structure
- [ ] Implement statistics cards component
- [ ] Build recent cases list
- [ ] Create quick actions panel
- [ ] Add responsive design
- [ ] Implement loading states
- [ ] Add error boundaries
- [ ] Write unit tests

### UI/UX Guidelines:
- Use sharp blues for primary actions and headers
- Use subtle oranges for secondary elements and highlights
- Ensure responsive design for all screen sizes
- Implement smooth loading transitions
- Add hover states for interactive elements
