### ISSUE TITLE
Setup Backend API and Ollama Integration

### ISSUE THREAD

**Issue by jreyes-beyond** [jreyes-beyond/lexarb#7]
### Core Backend Features:
1. FastAPI Setup
   - Authentication system
   - Database models
   - API routing
   - Middleware configuration

2. Ollama Integration
   - Document analysis pipeline
   - Case summarization
   - Email processing
   - Award drafting assistance

3. Email Automation
   - Unique email generation per case
   - Email parsing and processing
   - Document extraction
   - Automated notifications

#### FastAPI Setup:
```python
requirements.txt additions:
- fastapi
- uvicorn
- sqlalchemy
- pydantic
- python-jose[cryptography]
- passlib[bcrypt]
- python-multipart
- aiosmtplib
```

#### Database Models:
- Cases
- Documents
- Users
- Communications
- Awards

### Tasks:
- [ ] Set up FastAPI project structure
- [ ] Configure database and models
- [ ] Implement authentication system
- [ ] Set up Ollama integration
- [ ] Create email automation system
- [ ] Implement document processing pipeline
- [ ] Add error handling and logging
- [ ] Write API tests

### API Endpoints to Implement:
1. Authentication
   - /auth/login
   - /auth/register
   - /auth/refresh-token

2. Case Management
   - /cases/
   - /cases/{case_id}
   - /cases/{case_id}/documents
   - /cases/{case_id}/timeline

3. Document Processing
   - /documents/upload
   - /documents/analyze
   - /documents/categorize

4. Email Integration
   - /email/process
   - /email/send
   - /email/parse-attachment

### Security Considerations:
- Implement JWT authentication
- Set up CORS properly
- Handle file upload security
- Implement rate limiting
- Add input validation
- Set up proper error handling
